spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5439/mydb?currentSchema=${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      continue-on-error: false

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
    default-schema: tns_energy

security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_DURATION}
    refresh: ${JWT_REFRESH_DURATION}
