spring:
  datasource:
    url: abc
    username: abc
    password: abc
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:/liquibase/changesets/db.changelog.yaml
#    enabled: true
#    default-schema: challenge_arena
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_DURATION}
    refresh: ${JWT_REFRESH_DURATION}